### ISSUE TITLE
补全实现query_tick_history

### ISSUE THREAD

**Issue by lanceyliao** [vnpy/vnpy_tqsdk#10]
https://github.com/ethonchen/vnpy_tqsdk/blob/main/vnpy_tqsdk/tqsdk_datafeed.py

**Comment by lanceyliao** [comment]
https://github.com/ethonchen/vnpy_tqsdk/blob/96b6763a63f5d60d0a1ec3799d167e8e98faaf4d/vnpy_tqsdk/tqsdk_datafeed.py#L81

**Comment by lanceyliao** [comment]
https://github.com/ethonchen/vnpy_tqsdk/blob/96b6763a63f5d60d0a1ec3799d167e8e98faaf4d/vnpy_tqsdk/tqsdk_datafeed.py#L81

**Comment by vnpy** [comment]
欢迎发个PR
